"""empty message

Revision ID: 3a2f34fbe310
Revises: 944fc9634ded
Create Date: 2022-12-18 19:22:18.818485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2f34fbe310'
down_revision = '944fc9634ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.String(length=35), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operacao')
    # ### end Alembic commands ###
