"""empty message

Revision ID: 77090d14f04a
Revises: 3a2f34fbe310
Create Date: 2023-01-08 19:45:16.757438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77090d14f04a'
down_revision = '3a2f34fbe310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operacao', type_='foreignkey')
    op.drop_column('operacao', 'conta_id')
    # ### end Alembic commands ###
